on:
   workflow_call:
    inputs:
        environment_name:
            required: true
            type: string

jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{inputs.environment_name}}"



               