on:
    push:
        branches: "*"

jobs:
    hello:
        env:
            BUILD_MODE: "Debug"
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{secrets.MY_NAME}}"
            - run: echo "${{env.BUILD_MODE}}"