on:
    push:
        branches: "*"

jobs: 
    caller:
        runs-on: ubuntu-latest
        steps: 
            - uses: ./.github/workflows/first.yml
              with:
                environment_name: production
        


